### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ghost** [AlphaReign/www-php#10]
Hey mate hope your well.
Do you know why it is that when trying to sort by tags, that only sorting by 720  and 1080p works? example link below.

https://alphareign.lol

**Comment by ghost** [comment]
nevermind it seems in middleware/views.php it doesnt like the tags in upercase

**Comment by ghost** [comment]
still have a issue with this code. still outputs the tags in uppercase. could you tell me were i could transform them into lowercase please.

```
 {{#type}}
                                <a href="?{{getURLTypeless}}type={{type}}" class="label label-primary">{{type}}</a>
                            {{/type}}
                            {{#type}}
                                {{#categories}}<a href="?{{getURLCatless}}category={{.}}" class="label label-success">{{.}}</a> {{/categories}}
                            {{/type}}
                            {{#type}}
                                {{#tags}}<a href="?{{getURLTagless}}tag={{.}}" class="label label-info">{{.}}</a> {{/tags}}
                            {{/type}}
```

**Comment by ghost** [comment]
fixed by adding this code to handlers/search/query.php

$this->params->tag = strtolower($this->params->tag);

**Comment by Raxvis** [comment]
Good catch!
