### ISSUE TITLE
How to become admin

### ISSUE THREAD

**Issue by ghost** [AlphaReign/www-php#8]
Just wondering what steps you take to become a admin in this script?
kind regards

**Comment by Raxvis** [comment]
Just set is_admin = 1 in the mysql database on your user.

**Comment by ghost** [comment]
I registered but don't see such row in mysql

**Comment by Raxvis** [comment]
Do you have a users table?

**Comment by ghost** [comment]
![jg6t78](https://user-images.githubusercontent.com/21961112/37258788-da343b46-2574-11e8-9715-50b9bf644e05.jpg)

ive attached an image

**Comment by Raxvis** [comment]
Add a column called is_admin that is a bit / Boolean column

**Comment by ghost** [comment]
Yep did that but I see no change to my account ?

**Comment by ghost** [comment]
What changes am i meant to see?

kind regards

**Comment by Raxvis** [comment]
You should be able to see the ability to update a torrent, or delete /
block a torrent

**Comment by ghost** [comment]
Nope afraid it remains the same as standard account :/

**Comment by ghost** [comment]
Sorry it seems i can see update button but not ability to delete?

**Comment by Raxvis** [comment]
It might be a report button.  But the ability to update works means you should be admin

**Comment by ghost** [comment]
yup its the flag button sorry

**Comment by ghost** [comment]
Thanks mate
